"""empty message

Revision ID: 085e66cd7e10
Revises: 
Create Date: 2019-10-27 23:28:58.547575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085e66cd7e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'restaurant', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='unique')
    # ### end Alembic commands ###
